---
#File: roles/cloud/digitalocean/tasks/main.yml
#Setup required systems on Digital Ocean
# Arguments:
#	grouplist	: the name of an inventory group that will be used as a source of hosts to create

- name: Double check that API Token was set properly
  fail: msg='Environment Variable "DO_API_TOKEN" Must Be Set Before Running'
  when: do_token == ""

- name: ensure key exists at DigitalOcean
  digital_ocean: >
    state=present
    command=ssh
    name=iMac
    ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
    api_token={{ do_token }}
  register: my_ssh_key
  #TODO: make the 'name' value based on hostname

- name: Create Droplet Hosts
  digital_ocean: >
    state=present
    command=droplet
    name={{ item }}
    unique_name=yes
    size_id=512mb
    region_id=tor1
    image_id=ubuntu-16-04-x64
    ssh_key_ids={{ my_ssh_key.ssh_key.id }}
    api_token={{ do_token }}
  with_items: "{{ groups[grouplist] }}"
  register: droplet_details

- name: Register New Systems with Ansible Live Inventory
  add_host: hostname={{ item.droplet.ip_address }} groups=DO-{{ grouplist }}
  with_items: "{{ droplet_details.results }}"
  no_log: true
  #no_log is used to avoid a bunch of data on screen

#Notes: 
# https://gist.github.com/sheldonh/7203512
# searcho for 'ssh': http://docs.ansible.com/ansible/wait_for_module.html
- name: Wait for SSH to come online on new systems
  wait_for: host={{item}} port=22 search_regex="OpenSSH"
  with_items: "{{ groups['DO-' + grouplist] }}"

#replaced by above wait_for task
#- name: Pause to let systems boot
#  pause: seconds=15
