---
#File: roles/cloud/digitalocean/tasks/main.yml
#Setup required systems on Digital Ocean
# Arguments:
#	grouplist	: the name of an inventory group that will be used as a source of hosts to create

- name: Double check that API Token was set properly
  fail: msg='Environment Variable "DO_API_TOKEN" Must Be Set Before Running'
  when: do_token == ""

- name: ensure key exists at DigitalOcean
  digital_ocean: >
    state=present
    command=ssh
    name=iMac
    ssh_pub_key={{ lookup('file', '~/.ssh/id_rsa.pub') }}
    api_token={{ do_token }}
  register: my_ssh_key
  #TODO: make the 'name' value based on hostname

- name: Create Droplet Hosts
  digital_ocean: >
    state=present
    command=droplet
    name={{ item }}
    unique_name=yes
    size_id=512mb
    region_id=tor1
    image_id=ubuntu-16-04-x64
    ssh_key_ids={{ my_ssh_key.ssh_key.id }}
    api_token={{ do_token }}
  with_items: "{{ groups[grouplist] }}"
  register: droplet_details

- name: Register New Systems with Ansible Live Inventory
  add_host: hostname={{ item.droplet.ip_address }} groups=DO-{{ grouplist }}
  with_items: "{{ droplet_details.results }}"
  no_log: true
  #no_log is used to avoid a bunch of data on screen

#if there is a floating IP associated with the host, assign it as appropriate
#See: https://developers.digitalocean.com/documentation/v2/#assign-a-floating-ip-to-a-droplet
# curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer b7d03a6947b217efb6f3ec3bd3504582" -d '{"type":"assign","droplet_id":8219222}' "https://api.digitalocean.com/v2/floating_ips/45.55.96.47/actions" 
# TODO: change the HEADER format over to the 'headers' format(once I find a good example)
- name: Setting up Floating IP Addressing
  uri: 
    url: "https://api.digitalocean.com/v2/floating_ips/{{hostvars[item.item].floating_ip}}/actions"
    body: '{"type":"assign","droplet_id":{{item.droplet.id}} }'
    body_format: json
    HEADER_Authorization: "Bearer {{do_token}}"
    status_code: 200,201
  with_items: "{{ droplet_details.results }}"
  when: hostvars[item.item].floating_ip is defined

#Notes: 
# https://gist.github.com/sheldonh/7203512
# searcho for 'ssh': http://docs.ansible.com/ansible/wait_for_module.html
- name: Wait for SSH to come online on new systems
  wait_for: host={{item}} port=22 search_regex="OpenSSH"
  with_items: "{{ groups['DO-' + grouplist] }}"

- name: Pausing to let services settle
  pause: seconds=5
