---
#File: roles/tools/pelican/tasks/main.yml
#Install and initially configure pelican

#Let's start with supporting packages
- name: Install Pelican Supporting Packages
  apt: name='{{item}}' update_cache=yes state=present
  with_items:
   - python-pip
   - pandoc

- name: Install Pelican and tools via PIP
  pip: name='{{item}}'
  with_items:
   - pelican
   - Markdown
   - BeautifulSoup4
   - lxml
   #- Typogrify

