---
#File: roles/webserver/lighttpd/tasks/main.yml
#Install and initially configure lighttpd

#Let's start with the package install
- name: Install LigHTTPd
  apt: name=lighttpd update_cache=yes state=present

#TODO: see if we can be more exclisive on static only: https://astrocyte.no-ip.org/output/pelican-blog-software-running-on-lighttpd.html

#copy over a modified evhost config
# websites need to be in /var/www/html/%0/htdocs/ where %0 is domain.tld
# see: https://www.linode.com/docs/websites/lighttpd/use-lighttpd-web-server-on-ubuntu-16-04
- name: Copy updated evhosts config
  copy: src='10-evhost.conf' dest='/etc/lighttpd/conf-available/10-evhost.conf' owner=root group=root mode=0644
  notify: restart lighttpd

#Enable the evhost option
- name: Enabling LigHTTPd evhosts
  command: "lighttpd-enable-mod evhost"
  args:
    creates: "/etc/lighttpd/conf-enabled/10-evhost.conf"
  notify: restart lighttpd

#Update default page location
- name: Changing Default Page in LigHTTPd
  lineinfile: 
    dest: /etc/lighttpd/lighttpd.conf
    regexp: '^server.document-root'
    line: 'server.document-root        = "/var/www/html/jaredyoung.ca/htdocs"'
  notify: restart lighttpd

- name: Removing placeholder HTML page
  file: path=/var/www/html/index.lighttpd.html state=absent
